PreCommit:

  CustomScript:
    enabled: true
    description: 'Run CI script'
    required_executable: './scripts/cibuild'

  BundleCheck:
    enabled: true

  Eslint:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude: 'scripts/*'

  TrailingWhitespace:
    enabled: true
